version : '3'
services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: "routine"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    networks:
      - backend-routine
    volumes:
      - "./schema.sql:/docker-entrypoint-initdb.d/1.sql"
      - "db-config:/etc/mysql"
      - "db-data:/var/lib/mysql"
    
volumes:
  db-data:
  db-config:
networks:
  backend-routine:
